/**
* Copyright (c) 2004 Mega Enterprise Co., Ltd.
*
* @author 김병수 <kcando@megaking.co.kr>
*/
// PoporuErrorCode.h
//  - Arcade 에러 코드 정의
//
#if !defined(INCLUDED_POPORUERRORCODE)
#define INCLUDED_POPORUERRORCODE

#include "../ErrorCode.h"

namespace skynet
{

/// 아이디 또는 비번이 일치하지 않는다
DEFINE_ERRORCODE EC_INVALID_ACCOUNT = -10;
/// 같은 계정으로 이미 로그인 중이다
DEFINE_ERRORCODE EC_ALREADY_LOGIN = -20;
/// 채널 서버가 더이상 사용자를 수용할 수 없다
DEFINE_ERRORCODE EC_TOO_MANY_USERS = -30;
/// 잘못된 게임타입
DEFINE_ERRORCODE EC_INVALID_GAMETYPE = -36;

/// 사용자를 찾을 수 없다
DEFINE_ERRORCODE EC_USER_NOT_FOUND = -40;
/// 카드 번호가 잘못되었다(카드가 존재하지 않는다)
DEFINE_ERRORCODE EC_USER_INVALID_CARD_NUMBER = -45;

/// 더이상 (게임)방을 만들수 없다.
DEFINE_ERRORCODE EC_ROOM_LIMIT_EXCEEDED = -50;
/// 방을 찾을 수 없다
DEFINE_ERRORCODE EC_ROOM_NOT_FOUND = -60;
/// 방 비번이 일치하지 않는다
DEFINE_ERRORCODE EC_ROOM_INVALID_PASSWORD = -70;
/// 방(로비)에 이미 접속 중이다
DEFINE_ERRORCODE EC_ROOM_ALREADY_JOINED = -80;
/// 방에 비어 있는 자리가 없다
DEFINE_ERRORCODE EC_ROOM_NO_MORE_SEAT = -90;
/// BAN 당한 방에는 다시 들어갈 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_JOIN_WHEN_BANNED = -97;
/// 게임 중인 방은 입장할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_JOIN_WHEN_PLAYING = -98;
/// 게임 중인 방에서 퇴장할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_PART_WHEN_PLAYING = -99;
/// 방에서 사용자를 찾을 수 없다
DEFINE_ERRORCODE EC_ROOM_USER_NOT_FOUND = -100;
/// 게임을 시작할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_START = -110;
/// 게임을 시작할 수 없다(게임을 시작하기 전에 준비를 해야 한다)
DEFINE_ERRORCODE EC_ROOM_MUST_READY_BEFORE_START_GAME = -111;
/// 게임을 중단할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_STOP = -120;
/// 잘못된 게임 결과
DEFINE_ERRORCODE EC_INVALID_GAME_RESULT = -125;
/// 관전 대기자로 전환할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_LEAVE_SLOT = -130;
/// 슬롯 대기자로 전환할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_ENTER_SLOT = -140;
/// 1인당 방 하나만 만들 수 있다
DEFINE_ERRORCODE EC_ROOM_CREATE_ONLY_ONE = -160;
/// 1인당 방 하나에만 참여할 수 있다 
DEFINE_ERRORCODE EC_ROOM_JOIN_ONLY_ONE = -170;
/// 플레이어의 UDP 정보가 설정되지 않아서 게임을 시작할 수 없다
DEFINE_ERRORCODE EC_UDP_ADDRESS_IS_NOT_SETTED = -175;
/// 관전 중이어서 게임을 시작할 수 없다
DEFINE_ERRORCODE EC_OBSERVING_IS_NOT_FINISHED = -177;

/// 사용자를 초대할 수 없다(사용자가 없거나 방에 이미 접속 중인 경우)
DEFINE_ERRORCODE EC_CANT_INVITE_ROOM_USER = -190;

/// 게임 모드를 변경할 수 없다(권한; 방 상태; 인원 문제 등으로 인해)
DEFINE_ERRORCODE EC_CANT_CHANGE_GAME_MODE = -200;

/// 대전 신청을 할 수 없다
DEFINE_ERRORCODE EC_CANT_CHALLENGE = -210;

/// 게임 모드가 잘못되어 방을 생성할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_CREATE_ROOM_BECAUSE_INVALID_GAME_MODE = -220;
/// 코인이 없는 경우 방을 만들 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_CREATE_ROOM_BECAUSE_NO_COIN = -221;
/// 방 생성 자격 조건이 되지 않아 방을 생성할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_CREATE_ROOM_BECAUSE_NO_PERMISSION = -230;
/// 방 참여 자격 조건이 되지 않아 방 참여할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_JOIN_ROOM_BECAUSE_NO_PERMISSION = -240;

/// RP 제한으로 방을 생성할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_CREATE_ROOM_BECAUSE_OVER_RP = -241;
/// RP 제한으로 방에 입장할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_JOIN_ROOM_BECAUSE_OVER_RP = -242;

/// RP 제한으로 방을 생성할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_CREATE_ROOM_BECAUSE_SHORTAGE_RP = -243;
/// RP 제한으로 방에 입장할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_JOIN_ROOM_BECAUSE_SHORTAGE_RP = -244;


/// 코인을 넣을 수 없다
DEFINE_ERRORCODE EC_CANT_INSERT_COIN = -250;

/// 게임을 준비할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_READY = -300;
/// 플레이어는 게임라운드를 선택할 수 없다
DEFINE_ERRORCODE EC_PLAYER_CANT_SELECT_GAMEROUND = -310;
/// 게임라운드를 찾을 수 없다
DEFINE_ERRORCODE EC_GAMEROUND_NOT_FOUND = -312;
/// 이미 게임라운드를 선택하였다(단 한번만 선택할 수 있다)
DEFINE_ERRORCODE EC_ALREADY_SELECT_GAMEROUND = -314;
/// 관전할 수 없는 게임라운드(토너먼트 부전승 게임라운드)
DEFINE_ERRORCODE EC_CANT_OBSERVE_UNEARNEDWIN_GAMEROUND = -315;

/// 게임타이틀이 다르기 때문에 방에 입장할 수 없다
DEFINE_ERRORCODE EC_ROOM_CANT_JOIN_BECAUSE_DIFFERENT_GAMETYPE = -320;

/// 코인을 이동할 수 없다
DEFINE_ERRORCODE EC_CANT_MOVE_COIN = -330;
/// 보관함에 보관된 코인이 있다.
DEFINE_ERRORCODE EC_HAVE_COIN_BAG	= -331;

/// 소유중인 케릭터 카드에 코인이 남아 있다.
DEFINE_ERRORCODE EC_CHARACTER_CARD_COIN	= -332;

/// 유저가 선택한 카드가 DB에 없다.
DEFINE_ERRORCODE EC_CHARACTER_CARD_NOT_FOUND = -333;

/// 채팅이 금지되었다
DEFINE_ERRORCODE EC_CHATTING_IS_DISABLED = -340;

// = 아이템 관련

/// 잘못된 카드 슬롯 인덱스
DEFINE_ERRORCODE EC_INVALID_CARDSLOTINDEX = -10000;

/// 잘못된 ItemId
DEFINE_ERRORCODE EC_INVALID_ITEMID = -10010;

/// 이미 사용 중인(슬롯에 꽂힌) 아이템
DEFINE_ERRORCODE EC_ALREADY_USED_ITEM = -10020;

/// 카드 슬롯이 꽉 찼다
DEFINE_ERRORCODE EC_CARDSLOT_IS_FULL = -10030;

/// 같은 타입의 아이템을 동시에 장착할 수 없다
DEFINE_ERRORCODE EC_CANT_ATTACH_SAME_TYPE_ITEM = -10040;

/// 파워(웹) 아이템은 장착할 수 없다
DEFINE_ERRORCODE EC_CANT_ATTACH_POWERITEM = -10050;

/// 장착 안된 아이템은 삭제할 수 없다
DEFINE_ERRORCODE EC_SLOTITEM_IS_NOT_ATTACHED = -10060;

// = 메신저 관련 에러

DEFINE_ERRORCODE EC_IM_START = -30000;
/// 친구가 이미 등록되어 있다
DEFINE_ERRORCODE EC_IM_ALREADY_REGISTERED_BUDDY = (EC_IM_START - 1);
/// 너무 많은 친구가 등록되어 있어서 더이상 등록할 수 없다
DEFINE_ERRORCODE EC_IM_CANT_REGISTER_BUDDY_BECAUSE_TOO_MANY_BUDDY =
    (EC_IM_START - 2);
/// 나쁜 친구(상대방이 나쁜 친구로 등록해도)와는 귓속말을 할 수 없다
DEFINE_ERRORCODE EC_IM_CANT_WHISPER_WITH_BAD_BUDDY = (EC_IM_START - 3);
/// 나쁜 친구(상대방이 나쁜 친구로 등록해도)를 초대할 수 없다
DEFINE_ERRORCODE EC_IM_CANT_INVITE_BAD_BUDDY = (EC_IM_START - 4);
/// 자기 자신을 등록할 수 없다
DEFINE_ERRORCODE EC_IM_CANT_REGISTER_YOURSELF = (EC_IM_START - 5);

/// 서버 내부 결함
DEFINE_ERRORCODE EC_SERVER_FAULT = -40000;

/// 데이터베이스 관련 에러
DEFINE_ERRORCODE EC_DATABASE_FAULT = -50000;

/// 메니저 서버관련 에러 different 
//메니저 쿠키가 다르다
DEFINE_ERRORCODE EC_DIFFERENT_MANAGERCOOKIE = -60000;

//메니저 DB 유저아이디 다르다.
DEFINE_ERRORCODE EC_DEFFERENT_MANAGERUSERID = -61000;
//메니저 DB 이미 있는 유저 .
DEFINE_ERRORCODE EC_EXISTS_USERID = -61001;
//메니저 DB 유저PW 다르다.
DEFINE_ERRORCODE EC_DEFFERENT_MANAGERPASSWORD = -61100;
//메니저 DB 이미 접속중
DEFINE_ERRORCODE EC_MANAGERLOGIN_ALREADY = -61200;


//게임 체널에 아무도 없다.
DEFINE_ERRORCODE EC_NOT_ANY_USERS = -61300;
//잘못된 인증 타입
DEFINE_ERRORCODE EC_MISS_AUTHENTIC_MODE_TYPE = -61400;
//기능을 다루는 권한이 없다. 
DEFINE_ERRORCODE EC_ASK_AUTHORITY = -61500;
// 잘못된 파일 핸들
DEFINE_ERRORCODE EC_WRONG_FILE_HANDLE = -61600;
// 파일 쓰기 에러
DEFINE_ERRORCODE EC_WRITE_FILE_ERROR = -61601;
// 파일 완성시 사이즈가 다르다.
DEFINE_ERRORCODE EC_DEFFERENT_COMPLETION_FILE_SIZE = -61602;

DEFINE_ERRORCODE EC_FIND_NOT_SERVER = -61700;

DEFINE_ERRORCODE EC_ACTION_SERVICE_BAD = -61800;

inline bool isAlreadyLogin(ErrorCode ec) {
    return ec != EC_ALREADY_LOGIN;
}
} // namespace skynet

#endif // !defined(INCLUDED_POPORUERRORCODE)
