//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 62CutPoker.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SPOKER2_DIALOG              102
#define IDD_62CUTPOKER_DIALOG           102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_LOBY_DIALOG                 103
#define IDD_GAME_DIALOG                 104
#define IDD_TITLE_DIALOG                105
#define IDR_MAINFRAME                   128
#define IDD_NEWACCOUNT_DIALOG           129
#define IDB_IMAGE_ROOM                  130
#define IDB_IMAGE_USER                  131
#define IDB_BITMAP_LOBYBACK             132
#define IDB_BTN_NOITEM1                 132
#define IDC_CURSOR_SELECT               133
#define IDB_BTN_NOITEM2                 133
#define IDD_MSG_DIALOG                  134
#define IDC_CURSOR_HAND                 134
#define IDB_BTN_NOITEM3                 134
#define IDD_CREATEROOM_DIALOG           135
#define IDC_CURSOR_MOVE                 135
#define IDB_BTN_NOITEM4                 135
#define IDC_CURSOR_ADJUSTSIZE           136
#define IDD_NEW_ASKCHARGEDLG            136
#define IDB_CREATEROOM2                 137
#define IDC_CURSOR_WAIT                 137
#define IDB_CREATEROOM3                 138
#define IDB_CREATEROOM4                 139
#define IDB_BTN_START1                  139
#define IDB_LOGOUT1                     140
#define IDB_LOGOUT2                     141
#define IDB_LOGOUT3                     142
#define IDB_LOGOUT4                     143
#define IDB_BTN_START2                  143
#define IDB_ENTERROOM1                  144
#define IDB_ENTERROOM2                  145
#define IDB_ENTERROOM3                  146
#define IDB_ENTERROOM4                  147
#define IDB_BTN_START3                  147
#define IDB_CHANGEPROFILE4              148
#define IDB_BTN_START4                  148
#define IDB_BTN_ITEM1                   149
#define IDB_BTN_ITEM2                   150
#define IDB_CHANGEPROFILE1              151
#define IDB_VIEWPROFILE1                152
#define IDB_VIEWPROFILE2                153
#define IDB_VIEWPROFILE3                154
#define IDB_VIEWPROFILE4                155
#define IDB_BTN_ITEM3                   155
#define IDB_HOMEPAGE1                   156
#define IDB_HOMEPAGE2                   157
#define IDB_HOMEPAGE3                   158
#define IDB_HOMEPAGE4                   159
#define IDB_BTN_ITEM4                   159
#define IDB_BTN_PRACTICE1               160
#define IDB_BTN_PRACTICE2               161
#define IDB_BTN_PRACTICE3               162
#define IDB_BTN_PRACTICE4               163
#define IDB_CHANGEPROFILE2              164
#define IDB_CHANGEPROFILE3              165
#define IDD_INVITE_DIALOG               166
#define IDD_SELECTCARD_DIALOG           167
#define IDD_SELECTGOSTOP_DIALOG         168
#define IDD_PROFILE_DIALOG              170
#define IDB_PROFILEBACK                 171
#define IDB_PROFILECLOSE1               172
#define IDB_PROFILECLOSE2               173
#define IDB_PROFILECLOSE3               174
#define IDB_CREATEROOM_CANCEL1          179
#define IDB_CREATEROOM_CANCEL2          180
#define IDB_CREATEROOM_CANCEL3          181
#define IDD_CHANGECAHR_DIALOG           182
#define IDB_CHANGECHARBACK              183
#define IDB_CHANGECHAR_LEFT1            184
#define IDB_CHANGECHAR_LEFT2            185
#define IDB_CHANGECHAR_LEFT3            186
#define IDB_CHANGECHAR_RIGHT1           188
#define IDB_CHANGECHAR_RIGHT2           189
#define IDB_CHANGECHAR_RIGHT3           190
#define IDB_CHANGECHAR_OK1              192
#define IDB_CHANGECHAR_OK2              193
#define IDB_CHANGECHAR_OK3              194
#define IDB_CHANGECHAR_CANCEL1          195
#define IDB_CHANGECHAR_CANCEL2          196
#define IDB_CHANGECHAR_CANCEL3          197
#define IDB_LEVEL15                     198
#define IDB_BTN_ATEAM1                  200
#define IDD_GAMERESULT_DIALOG           201
#define IDB_BTN_ATEAM2                  201
#define IDB_GAMERESULTBACK              202
#define IDB_BTN_ATEAM3                  202
#define IDB_GAMERESULT_OK1              203
#define IDB_BTN_BTEAM1                  203
#define IDB_GAMERESULT_OK2              204
#define IDB_BTN_BTEAM2                  204
#define IDB_GAMERESULT_OK3              205
#define IDB_BTN_BTEAM3                  205
#define IDB_SELECTGOSTOPBACK            207
#define IDB_BTN_CTEAM1                  207
#define IDB_SELECTGOSTOP_GO1            208
#define IDB_BTN_CTEAM2                  208
#define IDB_SELECTGOSTOP_GO2            209
#define IDB_BTN_CTEAM3                  209
#define IDB_SELECTGOSTOP_GO3            210
#define IDB_SELECTGOSTOP_STOP1          211
#define IDB_BTN_SINGLE1                 211
#define IDB_SELECTGOSTOP_STOP2          212
#define IDB_BTN_SINGLE2                 212
#define IDB_SELECTGOSTOP_STOP3          213
#define IDB_BTN_SINGLE3                 213
#define IDB_SELECTCARDBACK              214
#define IDB_BTN_FULLSCREEN1             214
#define IDB_CHANGECARDPOSBACK           215
#define IDB_BTN_FULLSCREEN2             215
#define IDB_CHANGECARDPOS_OK1           216
#define IDB_BTN_FULLSCREEN3             216
#define IDB_CHANGECARDPOS_OK2           217
#define IDB_BTN_WINDOW1                 217
#define IDB_CHANGECARDPOS_OK3           218
#define IDB_BTN_WINDOW2                 218
#define IDB_CHANGECARDPOS_CANCEL1       219
#define IDB_BTN_WINDOW3                 219
#define IDB_CHANGECARDPOS_CANCEL2       220
#define IDB_BTN_EXIT1                   220
#define IDB_CHANGECARDPOS_CANCEL3       221
#define IDB_BTN_EXIT2                   221
#define IDD_CHANGECARDPOS_DIALOG        222
#define IDB_BTN_EXIT3                   222
#define IDD_SENDINVITE_DIALOG           223
#define IDB_BTN_INVITE1                 223
#define IDD_RECVINVITE_DIALOG           224
#define IDB_BTN_INVITE2                 224
#define IDD_REFUSE_DIALOG               225
#define IDB_BITMAP_TITLEBACK            225
#define IDB_BTN_INVITE3                 225
#define IDB_ROOMINFO1                   226
#define IDB_ROOMINFO2                   227
#define IDB_ROOMINFO3                   228
#define IDB_ROOMINFO4                   229
#define IDB_BTN_FINDID1                 229
#define IDD_ROOMINFO_DIALOG             230
#define IDB_BTN_FINDID2                 230
#define IDB_ROOMINFOCLOSE1              231
#define IDB_ROOMINFOCLOSE2              232
#define IDB_ROOMINFOCLOSE3              233
#define IDB_ROOMINFOBACK                234
#define IDB_BTN_FINDID3                 234
#define IDR_ROOMMENU                    235
#define IDB_INVITEBACK                  236
#define IDB_BTN_MINIMIZE1               236
#define IDB_INVITE_PROFILEBTN1          237
#define IDB_INVITE_PROFILEBTN2          238
#define IDB_INVITE_PROFILEBTN3          239
#define IDB_INVITE_INVITEBTN1           240
#define IDB_INVITE_INVITEBTN2           241
#define IDB_INVITE_INVITEBTN3           242
#define IDB_BTN_MINIMIZE2               243
#define IDR_INVITEMENU                  244
#define IDB_BTN_MINIMIZE3               244
#define IDD_WHISPER_DIALOG              245
#define IDB_BTN_OPTION1                 245
#define IDD_MSGBOX                      246
#define IDB_BTN_OPTION2                 246
#define IDD_ROOMPASS_DIALOG             247
#define IDB_BTN_OPTION3                 247
#define IDD_DIALOG_CONFIG               248
#define IDB_BTN_BANISHVOTE1             248
#define IDB_CHANGEDISPLAY_WINDOW1       249
#define IDD_BADUSER                     249
#define IDB_CHANGEDISPLAY_WINDOW2       250
#define IDD_OPTION_DIALOG               250
#define IDB_CHANGEDISPLAY_WINDOW3       251
#define IDD_BANISHVOTE                  251
#define IDB_CHANGEDISPLAY_FULLSCREEN1   252
#define IDD_MYVOTE                      252
#define IDB_CHANGEDISPLAY_FULLSCREEN2   253
#define IDD_LOGIN_DIALOG                253
#define IDB_CHANGEDISPLAY_FULLSCREEN3   254
#define IDD_WEBPROFILE_DIALOG           254
#define IDB_BADUSER1                    255
#define IDB_BADUSER2                    256
#define IDD_ITEMLIST_DIALOG             256
#define IDB_BADUSER3                    257
#define IDD_ASKBUYITEM_DIALOG           257
#define IDB_BTN_BANISHVOTE2             258
#define IDD_GAMEITEM_DIALOG             258
#define IDB_BTN_BANISHVOTE3             259
#define IDD_PREMSERVICE_DIALOG          259
#define IDB_BTN_CSHOP1                  263
#define IDD_NOTICE_DIALOG               264
#define IDB_BTN_CSHOP3                  266
#define IDB_BTN_CSHOP2                  267
#define IDB_IMAGE_CHECK                 268
#define IDB_IMAGE_CHAN                  269
#define IDB_TITLE_REFRESH1              270
#define IDB_TITLE_REFRESH2              271
#define IDB_TITLE_REFRESH3              272
#define IDB_TITLE_OPTION1               273
#define IDB_TITLE_OPTION2               274
#define IDB_TITLE_OPTION3               275
#define IDB_TITLE_EXIT1                 276
#define IDB_TITLE_EXIT2                 277
#define IDB_TITLE_EXIT3                 278
#define IDB_TITLE_WINDOW1               279
#define IDB_TITLE_WINDOW2               280
#define IDB_TITLE_WINDOW3               281
#define IDB_TITLE_ENTERCHAN1            282
#define IDB_TITLE_ENTERCHAN2            283
#define IDB_TITLE_ENTERCHAN3            284
#define IDB_TITLE_FULLSCREEN1           285
#define IDB_TITLE_FULLSCREEN2           286
#define IDB_TITLE_FULLSCREEN3           287
#define IDB_TITLE_FINDID1               288
#define IDB_TITLE_FINDID2               289
#define IDB_TITLE_FINDID3               290
#define IDB_OPTION_OK1                  291
#define IDB_OPTION_OK2                  292
#define IDB_OPTION_OK3                  293
#define IDB_OPTION_CANCEL1              294
#define IDB_OPTION_CANCEL2              295
#define IDB_OPTION_CANCEL3              296
#define IDB_AGE19                       297
#define IDD_ADMIN_MESSAGE               298
#define IDD_ADMIN_TITLE                 299
#define IDD_GAME_ITEM_START_DLG         300
#define IDD_GAME_ITEM_DLG               301
#define IDB_ITEM_USE1                   303
#define IDB_ITEM_USE3                   304
#define IDB_ITEM_USE2                   305
#define IDB_ITEM_CANCEL3                307
#define IDB_ITEM_CANCEL2                308
#define IDB_ITEM_CANCEL1                309
#define IDD_DLG_SELCARD                 310
#define IDD_WIN_CASE                    313
#define IDB_BTN_HIGH3                   315
#define IDB_QUICKSTART1                 316
#define IDB_QUICKSTART3                 317
#define IDB_QUICKSTART2                 318
#define IDB_BTN_OPTIONLOBY3             319
#define IDB_BTN_OPTIONLOBY2             320
#define IDB_BTN_OPTIONLOBY1             321
#define IDB_BTN_EXITL3                  322
#define IDB_BTN_EXITL2                  323
#define IDB_BTN_EXITL1                  324
#define IDB_BTN_HIGH2                   325
#define IDB_BTN_HIGH1                   326
#define IDB_BTN_SWING3                  327
#define IDB_BTN_LOW2                    328
#define IDB_BTN_LOW3                    329
#define IDB_BTN_SWING1                  330
#define IDB_BTN_SWING2                  331
#define IDB_BTN_LOW1                    332
#define IDD_DIALOG_RESULTHI             333
#define IDD_DIALOG_RESULTHILOW          334
#define IDB_BTN_RESULTOK3               338
#define IDB_BTN_RESULTOK1               339
#define IDB_BTN_RESULTOK4               340
#define IDB_BTN_RESULTOK2               341
#define IDD_ORING                       348
#define IDB_BTN_ORINGCANCEL3            349
#define IDB_BTN_ORINGOK2                350
#define IDB_BTN_ORINGOK3                351
#define IDB_BTN_ORINGCANCEL1            352
#define IDB_BTN_ORINGCANCEL2            353
#define IDB_BTN_ORINGOK1                354
#define IDB_BTN_LEVEL4                  362
#define IDB_BTN_LEVEL2                  363
#define IDB_BTN_LEVEL3                  364
#define IDB_BTN_LEVEL1                  365
#define IDD_DLG_SELCARDCHOICE           368
#define IDD_ROOMOPTIONDLG               369
#define IDB_IMAGE_GAMEITEMTAB           372
#define IDB_IMAGE_GAMEITEM              374
#define IDD_START_DIALOG                375
#define IDD_DLG_OBSERVER                376
#define IDD_BADUSER_WARNING             384
#define IDD_RESULT_FINDID               385
#define IDD_MSG_BOX                     386
#define IDC_CURSOR1                     388
#define IDD_DIG_LIMITMONEY              408
#define IDD_DIALOG_LIMITCONFIRM         409
#define IDD_DLG_MINIGAME                417
#define IDC_EDIT_ID                     1000
#define IDC_RICHEDIT_CHATVIEW           1000
#define IDC_EDIT_PASS                   1001
#define IDC_BUTTON_ATEAM                1001
#define IDC_BUTTON_LOGIN                1002
#define IDC_BUTTON_BTEAM                1002
#define IDC_EDIT_NEWID                  1003
#define IDC_BUTTON_CTEAM                1003
#define IDC_LIST_GAMEITEM               1003
#define IDC_BUTTON_IDSEARCH             1004
#define IDC_BUTTON_SINGLE               1004
#define IDC_EDIT_NEWPASS                1005
#define IDC_EDIT_CHATSEND               1005
#define IDC_EDIT_REPASS                 1006
#define IDC_EDIT_NAME                   1007
#define IDC_GAMEITEM_TAB                1007
#define IDC_RADIO_MEN                   1008
#define IDC_BUTTON_EXITGAME             1008
#define IDC_RADIO_WOOMEN                1009
#define IDC_EDIT_BIRTH1                 1010
#define IDC_BUTTON_PRACTICE             1010
#define IDC_STATIC_BANNER               1010
#define IDC_EDIT_BIRTH2                 1011
#define IDC_STATIC_GAMEBANNER           1011
#define IDC_EDIT_BIRTH3                 1012
#define IDC_EDIT1                       1012
#define IDC_EDIT_FINDID                 1012
#define IDC_EDIT_BANISHRESON            1012
#define IDC_EDIT_SERVERIP               1012
#define IDC_MES_ID                      1012
#define IDC_EDIT_ROOMNAME               1012
#define IDC_EDIT_EMAIL                  1013
#define IDC_STATIC_GAMEKIND             1013
#define IDC_EDIT_SERVERPORT             1013
#define IDC_COMBO_AREA                  1014
#define IDC_CHECK_OFFSNDFX              1014
#define IDC_COMBO_JOB                   1015
#define IDC_CHECK_OFFMUSIC              1015
#define IDC_COMBO_TARGETID              1015
#define IDC_EDIT_DESC                   1016
#define IDC_COMBO_RESON                 1016
#define IDC_PROGRESS                    1016
#define IDC_LIST_CHANNEL                1016
#define IDC_CHECK_NOINVITE              1016
#define IDC_CHECK_ISOPEN                1017
#define IDC_BUTTON_ENTER                1017
#define IDC_CHECK_NOWHISPER             1017
#define IDC_EDIT_LOBYSEND               1018
#define IDC_BUTTON_REFRESH              1018
#define IDC_BUTTON_DETAILPROFILE        1018
#define IDC_RICHEDIT_LOBYCHAT           1019
#define IDC_LIST_SHUTMOUSE              1020
#define IDC_BATRADIO1                   1020
#define IDC_BUTTON_HELP                 1020
#define IDC_LIST_USER                   1021
#define IDC_BATRADIO2                   1021
#define IDC_BUTTON_FIND                 1022
#define IDC_COMBOSTYLE                  1022
#define IDC_BUTTON_ITEM                 1022
#define IDC_LIST_ROOM                   1023
#define IDC_BUTTON_EXIT                 1023
#define IDC_BUTTON_SHOP                 1023
#define IDC_BUTTON_CASH                 1024
#define IDC_RADIO_STARTMODE1            1025
#define IDC_MES_CHAT                    1025
#define IDC_RADIO_STARTMODE2            1026
#define IDC_RADIO1                      1026
#define IDC_RADIO2                      1027
#define IDC_RADIO3                      1028
#define IDC_RADIO4                      1029
#define IDC_BUTTON_ENTERGAME            1030
#define IDC_BTN_EXIT                    1030
#define IDC_RADIO_FXKIND3               1030
#define IDC_BUTTON_CREATEROOM           1031
#define IDC_STATIC_MSG                  1031
#define IDC_BTN_SEND                    1031
#define IDC_RADIO_FXKIND4               1031
#define IDC_EDIT_ROOMTITLE              1032
#define IDC_BUTTON_LOGOUT               1032
#define IDC_BTN_HIDE                    1032
#define IDC_RADIO_FXKIND5               1032
#define IDC_BUTTON_HOMPAGE              1033
#define IDC_RADIO_WAITUSER              1033
#define IDC_BUTTON_CARD                 1033
#define IDC_COMBO_NAME                  1033
#define IDC_BUTTON_VIEWPROFILE          1034
#define IDC_RADIO_ALLUSER               1034
#define IDC_BUTTON_CHANGEPROFILE        1035
#define IDC_BUTTON_PROFILE              1035
#define IDC_STATIC_MES                  1035
#define IDC_BUTTON_INVITE               1036
#define IDC_BUTTON_ROOMINFO             1036
#define IDC_STATIC_TITLE                1036
#define IDC_LEFT_BUTTON                 1037
#define IDC_BUTTON_BADUSER              1037
#define IDC_RIGHT_BUTTON                1038
#define IDC_INVITEMSG_EDIT              1038
#define IDC_BUTTON_FINDID               1038
#define IDC_LIST_ITEM                   1038
#define IDC_OK                          1038
#define IDC_ROOMINFO_EDIT               1039
#define IDC_REFUSEMSG_EDIT              1040
#define IDC_BTN_USE                     1040
#define IDC_STATE_STATIC                1041
#define IDC_EDIT_WHISPER                1042
#define IDC_BUTTON_EXIT1                1042
#define IDC_EDIT_WHO                    1043
#define IDC_BUTTON_QUICKSTART           1043
#define IDC_EDIT_MSG                    1044
#define IDC_BUTTON_HIGH                 1044
#define IDC_COMBO_SECRET                1045
#define IDC_BUTTON_LOW                  1045
#define IDC_BUTTON_LEVEL                1045
#define IDC_EDIT_ROOMPASS               1046
#define IDC_BUTTON_SWING                1046
#define IDC_COMBO_MAXNUM                1047
#define IDC_CHECK_REFUSEINVITE          1048
#define IDC_COMBO_LEVEL                 1048
#define IDC_BUTTON_CHANGEDISPLAY        1049
#define IDC_COMBO_GAMEKIND              1049
#define IDC_RADIO_FULLSCREENMODE        1050
#define IDC_BUTTON_STARTGAME            1050
#define IDC_CHECK_REFUSEWHISPER         1050
#define IDC_COMBO_FORMKIND              1050
#define IDC_RADIO_WINDOWMODE            1051
#define IDC_EDIT_TARGETID               1051
#define IDC_BUTTON_ITEMWAR              1051
#define IDC_EDIT_REASON                 1052
#define IDC_BUTTON_NOITEMWAR            1052
#define IDC_CHECK_WHIS                  1052
#define IDC_CHECK_ANNOUNCE              1053
#define IDC_BUTTON_OPTION               1053
#define IDC_EDIT_MYID                   1054
#define IDC_BUTTON_MINIMIZE             1054
#define IDC_BUTTON_BANISHVOTE           1055
#define IDC_BUTTON_CLOSE                1055
#define IDC_BUTTON_ITEMBAG              1056
#define IDC_CHECK_SUPERMASTER           1057
#define IDC_RICHEDIT_NOTIC              1057
#define IDC_BUTTON_BANISH               1058
#define IDC_RADIO_FXKIND0               1059
#define IDC_BUTTON_LEFT                 1059
#define IDC_RADIO_FXKIND1               1060
#define IDC_BUTTON_RIGHT                1060
#define IDC_RADIO_FXKIND2               1061
#define IDC_LIST_OBR                    1061
#define IDC_BUTTON_LOBY                 1062
#define IDC_BUTTON2                     1063
#define IDC_BTN_CLOSE                   1063
#define IDC_BUTTON_ALLUSER              1063
#define IDC_BTN_OFFMUSIC                1063
#define IDC_BUTTON_CHOICE               1063
#define IDC_BUTTON_MYHOMPY              1064
#define IDC_BUTTON_CAPTURE              1065
#define IDC_BTN_PROFILE                 1065
#define IDC_BUTTON_IN                   1066
#define IDC_BUTTON_OUT                  1067
#define IDC_BUTTON_WAR                  1067
#define IDC_COMBO_MINIM                 1068
#define IDC_EDIT2                       1070
#define IDC_RADIO_USERCOUNT5            1071
#define IDC_RADIO_USERCOUNT6            1072
#define IDC_BUTTON_SHOWCARD             1073
#define IDC_BUTTON_NORMAL               1074
#define IDC_BUTTON_ALLKIND              1075
#define IDC_BTN_IMGCHECK                1076
#define IDC_BTN_OPTION_MAN1             1077
#define IDC_BTN_OPTION_MAN2             1078
#define IDC_BTN_OPTION_FEMALE1          1079
#define IDC_BTN_OPTION_FEMALE2          1080
#define IDC_BTN_OFFSNDFX                1081
#define IDC_BTN_STARTMODE1              1082
#define IDC_BTN_STARTMODE2              1083
#define IDC_BTN_NOINVITE                1084
#define IDC_BTN_NOWHISPER               1085
#define IDC_BTN_ANNOUNCE                1086
#define IDC_BTN_OPTION_MAN3             1086
#define IDC_BTN_OPTION_FEMALE3          1087
#define IDC_LIST2                       1092
#define IDC_BUTTON_SAFEANGEL            1093
#define IDC_BUTTON1                     1095
#define IDC_BUTTON3                     1098
#define IDC_MENUUSERINFO                32771
#define IDC_MENU_ADM_USERINFO           32771
#define IDC_MENUSENDWHISPHER            32772
#define IDC_MENU_ADM_SENDWHISPHER       32772
#define IDC_MENU_ADM_WARN_USER          32773
#define IDC_MENUROOMINFO                32774
#define IDC_MENU_ADM_ROOMINFO           32774
#define IDC_MENUINROOM                  32775
#define IDC_MENU_ADM_INROOM             32775
#define IDC_MENUMAKEROOM                32776
#define IDC_MENU_ADM_MAKEROOM           32776
#define IDC_MENU_ADM_NAME               32777
#define IDC_MENU_ADM_RENAMEROOM         32777
#define IDC_BUTTON_WHISPER              32778
#define IDC_MENU_ADM_DEL                32779
#define IDC_MENU_ADM_ROOMDEL            32779
#define IDC_MENU_ADM_WARN               32780
#define IDC_MENU_ADM_ROOMMASTER         32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        418
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
