//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by 62CutPokerServer.rc
//
#define IDOK2                           3
#define IDD_ABOUTBOX                    100
#define IDD_SPOKER2SERVER_FORM          101
#define IDD_62CUTPOKERSERVER_FORM       101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_TETRISTYPE                  129
#define IDD_CONFIG_DIALOG               130
#define IDD_DIALOG_MSG                  131
#define IDD_CONFIG2_DIALOG              132
#define IDD_STARTUP_DIALOG              133
#define IDD_CONFIG3_DIALOG              134
#define IDD_SETCHANINFO_DIALOG          135
#define IDD_SETCOLUMN_DIALOG            136
#define IDD_CONFIG_EVENT                137
#define IDD_CONFIG_DIALOG_JACKPOT       138
#define IDD_ADMIN_DLG                   140
#define IDD_DLG_ADMINMAN                141
#define IDD_CAPTURE_DIG                 143
#define IDD_SEARCH_DIG                  144
#define IDD_DIALOG_CONFIGSA             145
#define IDC_STATIC_IP                   1000
#define IDC_STATIC_DNS                  1001
#define IDC_RADIO_SSOBASE               1001
#define IDC_CHECK_SAFEANGEL             1001
#define IDC_STATIC_PORT                 1002
#define IDC_RADIO_DBBASE                1002
#define IDC_STATIC_TOTALUSER            1003
#define IDC_STATIC_SERVERNAME           1004
#define IDC_EDIT_SERVERNAME             1004
#define IDC_STATIC_GAMECODE             1005
#define IDC_EDIT_GAMECODE               1005
#define IDC_STATIC_SERVERCODE           1006
#define IDC_EDIT_SERVERCODE             1006
#define IDC_EDIT_SERVERPORT             1007
#define IDC_EDIT_SENDSERVERMSG          1007
#define IDC_RADIO_SENDTEXT              1008
#define IDC_RADIO_SENDMSGBOX            1009
#define IDC_BUTTON_SENDSERVERMSG        1010
#define IDC_STATIC_TEST                 1011
#define IDC_STATIC_MAXSTATE             1012
#define IDC_EDIT_LOGINMSG               1013
#define IDC_BUTTON_SETLOGINMSG          1014
#define IDC_RADIO_MODE80                1015
#define IDC_RADIO_SENDMSGBOTH           1015
#define IDC_RADIO_MODE8080              1016
#define IDC_STATIC_DISCARDNUM           1016
#define IDC_RADIO_MODEFREE              1017
#define IDC_EDIT_USERDB_DSN             1017
#define IDC_STATIC_TEST2                1017
#define IDC_STATIC_BADIPINFO            1018
#define IDC_EDIT_USERDB_TABLE           1018
#define IDC_EDIT_NOTICEURL              1018
#define IDC_RADIO_IPMODE0               1019
#define IDC_EDIT_USERDB_UID             1019
#define IDC_EDIT_MAXUSER                1019
#define IDC_RADIO_IPMODE1               1020
#define IDC_EDIT_DISCTARGETID           1020
#define IDC_EDIT_USERDB_PASS            1020
#define IDC_STATIC_MAXUSER              1020
#define IDC_RADIO_IPMODE2               1021
#define IDC_BUTTON_FORCEDISCONNECT      1021
#define IDC_EDIT_GAMEDB_DSN             1021
#define IDC_EDIT_INFO                   1021
#define IDC_EDIT_DBTHREADNUM            1021
#define IDC_EDIT_DELROOMNO              1022
#define IDC_STATIC_MSG                  1022
#define IDC_EDIT_GAMEDB_TABLE           1022
#define IDC_BUTTON_CONFIG               1022
#define IDC_EDIT_LOGINDBQUENUM          1022
#define IDC_BUTTON_FORCEDELROOM         1023
#define IDC_EDIT_GAMEDB_UID             1023
#define IDC_BUTTON_CONFIG2              1023
#define IDC_RADIO_EINTERLIMITMODE0      1023
#define IDC_EDIT_BANNERURL1             1023
#define IDC_STATIC_CONNECTSTATE         1024
#define IDC_EDIT_GAMEDB_PASS            1024
#define IDC_BUTTON_CONFIG3              1024
#define IDC_RADIO_EINTERLIMITMODE1      1024
#define IDC_EDIT_BANNERURL2             1024
#define IDC_EDIT_BADUSERDB_DSN          1025
#define IDC_EDIT_PROFILEURL             1025
#define IDC_BUTTON_EVENT                1025
#define IDC_EDIT_BADUSERDB_TABLE        1026
#define IDC_EDIT_LOCATIONURL            1026
#define IDC_EDIT_BADUSERDB_UID          1027
#define IDC_LIST_CHANINFO               1027
#define IDC_EDIT_ITEMURL                1027
#define IDC_EDIT_BADUSERDB_PASS         1028
#define IDC_EDIT_ITEMHELPURL            1028
#define IDC_EDIT_STATUSDB_DSN           1029
#define IDC_EDIT_DBTHREADNUM2           1029
#define IDC_EDIT_STATUSDB_TABLE         1030
#define IDC_EDIT_LOGINDBQUENUM2         1030
#define IDC_EDIT_STATUSDB_UID           1031
#define IDC_STATIC_MAXUSER2             1031
#define IDC_EDIT_STATUSDB_PASS          1032
#define IDC_CHECK_LOGINLIMIT            1032
#define IDC_EDIT_LEADERSJOIN            1032
#define IDC_EDIT_AVATARDB_DSN           1033
#define IDC_EDIT_CASHURL                1033
#define IDC_EDIT_AVATARDB_TABLE         1034
#define IDC_IPADDRESS1                  1034
#define IDC_CHECK_CHANLIMIT             1035
#define IDC_EDIT_AVATARDB_UID           1035
#define IDC_EDIT_LOGINLIMIT1            1036
#define IDC_EDIT_AVATARDB_PASS          1036
#define IDC_BUTTON_DEL                  1036
#define IDC_EDIT_LOGINLIMIT2            1037
#define IDC_CHECK_INITCONNECTSTATUS     1037
#define IDC_EDIT_ITEMDB_DSN             1037
#define IDC_BTN_ADMININFOSEND           1037
#define IDC_BUTTON_SELEDIT              1038
#define IDC_CHECK_DBCLOSE               1038
#define IDC_EDIT_ITEMDB_TABLE           1038
#define IDC_EDIT_CHANNAME               1039
#define IDC_EDIT_ITEMDB_UID             1039
#define IDC_CHECK_DBCLOSE2              1039
#define IDC_DATETIMEPICKER_STARTDATE    1039
#define IDC_EDIT_VALUE                  1040
#define IDC_EDIT_GAMEKIND               1040
#define IDC_EDIT_STATE                  1040
#define IDC_EDIT_ITEMDB_PASS            1040
#define IDC_DATETIMEPICKER_ENDDATE      1040
#define IDC_STATIC_COLUMNNAME           1041
#define IDC_EDIT_LIMIT1                 1041
#define IDC_EDIT_PREMIUMDB_DSN          1041
#define IDC_EDIT_LIMIT2                 1042
#define IDC_EDIT_HALF                   1042
#define IDC_EDIT_PREMIUMDB_TABLE        1042
#define IDC_CHECK_RUNEVENT              1042
#define IDC_EDIT_FULL                   1043
#define IDC_EDIT_GRADE                  1043
#define IDC_EDIT_JACKPOT                1043
#define IDC_EDIT_PREMIUMDB_UID          1043
#define IDC_EDIT_EVENTTICKETNUM         1043
#define IDC_EDIT_GOD                    1044
#define IDC_BUTTON_CONFIG4              1044
#define IDC_EDIT_JACKPOT_1              1044
#define IDC_EDIT_PREMIUMDB_PASS         1044
#define IDC_EDIT_MINUSERNUM             1044
#define IDC_EDIT_LEVEL1                 1045
#define IDC_BUTTON_JACKPOT              1045
#define IDC_EDIT_JACKPOT_2              1045
#define IDC_EDIT_PREMIPDB_DSN           1045
#define IDC_CHECK_NOEVENTTIME           1045
#define IDC_EDIT_LEVEL2                 1046
#define IDC_RADIO_EXIT30                1046
#define IDC_EDIT_JACKPOT_3              1046
#define IDC_EDIT_PREMIPDB_TABLE         1046
#define IDC_CHECK_AUTOEVENTEND          1046
#define IDC_EDIT_LEVEL3                 1047
#define IDC_RADIO_EXIT10                1047
#define IDC_EDIT_JACKPOT_4              1047
#define IDC_EDIT_PREMIPDB_UID           1047
#define IDC_EDIT_NOEVENTSTARTHOUR       1047
#define IDC_RADIO_EXIT5                 1048
#define IDC_EDIT_JACKPOT_5              1048
#define IDC_EDIT_CHBO                   1048
#define IDC_EDIT_PREMIPDB_PASS          1048
#define IDC_EDIT_NOEVENTHOUR            1048
#define IDC_RADIO_EXIT3                 1049
#define IDC_EDIT_LOGREC_DSN             1049
#define IDC_RADIO_EXIT1                 1050
#define IDC_EDIT_EVENTNOTICE            1050
#define IDC_EDIT_LOGREC_TABLE           1050
#define IDC_RADIO_EXIT30S               1051
#define IDC_EDIT_ROOMEVENTNOTICE        1051
#define IDC_EDIT_LOGREC_UID             1051
#define IDC_BUTTON_EXITOK               1052
#define IDC_EDIT_LOGREC_PASS            1052
#define IDC_BUTTON_EXITCANCEL           1053
#define IDC_EDIT_EVENT_DSN              1053
#define IDC_EDIT_MSCODE                 1054
#define IDC_EDIT_EVENT_TABLE            1054
#define IDC_COMBO_MSCODE                1055
#define IDC_BUTTON_EVENTSTATE           1055
#define IDC_EDIT_MAXPMONEY              1056
#define IDC_CHECK_ITEM                  1057
#define IDC_EDIT_SERVERINFO             1058
#define IDC_CHECK_LOG                   1058
#define IDC_EDIT_ID                     1059
#define IDC_EDIT_EVENT_UID              1059
#define IDC_BUTTON_ADD                  1060
#define IDC_EDIT_EVENT_PASS             1060
#define IDC_BUTTON_DELETE               1061
#define IDC_CHECK_EVENT                 1061
#define IDC_LIST_ADMIN                  1062
#define IDC_EDIT_STATIST_DSN            1062
#define IDC_BTN_DENYUSER                1063
#define IDC_EDIT_STATIST_TABLE          1063
#define IDC_CHECK_EXAM                  1064
#define IDC_EDIT_STATIST_UID            1064
#define IDC_EDIT_AGENTCONNECT           1065
#define IDC_EDIT_STATIST_PASS           1065
#define IDC_EDIT_LOGINLIMITGRADE        1066
#define IDC_CHECK_STATIST               1066
#define IDC_RADIO_JACKPOT               1067
#define IDC_EDIT_PREUSERMLLOG_DSN       1067
#define IDC_RADIO_JACKPOT1              1068
#define IDC_CHECK_AUTOINDEX             1068
#define IDC_EDIT_PREUSERMLLOG_TABLE     1068
#define IDC_EDIT_STARTVAL               1069
#define IDC_EDIT_PREUSERMLLOG_UID       1069
#define IDC_EDIT_CIPHER                 1070
#define IDC_EDIT_RATIO_CHOBO            1070
#define IDC_EDIT_PREUSERMLLOG_PASS      1070
#define IDC_EDIT_RATIO_JUNGSU           1071
#define IDC_CHECK_PREUSERMLLOG          1071
#define IDC_EDIT_RATIO_GOSU             1072
#define IDC_CHECK_SCRET                 1072
#define IDC_EDIT_RATIO_DOSIN            1073
#define IDC_CHECK_JUMP                  1073
#define IDC_EDIT_RATIO_FREE             1074
#define IDC_EDIT_BLOG                   1074
#define IDC_EDIT_ALLINCHARGE_DSN        1074
#define IDC_EDIT_RATIO_RSF              1075
#define IDC_CHECK_BLOG                  1075
#define IDC_EDIT_ALLINCHARGE_TABLE      1075
#define IDC_EDIT_RATIO_SF               1076
#define IDC_EDIT_LOGRANGE               1076
#define IDC_EDIT_ALLINCHARGE_UID        1076
#define IDC_EDIT_RATIO_FOURC            1077
#define IDC_LIST_USER                   1077
#define IDC_EDIT_ALLINCHARGE_PASS       1077
#define IDC_EDIT_JACKPOT_CHOBO          1078
#define IDC_CHECK_CAP                   1078
#define IDC_CHECK_ALLIN                 1078
#define IDC_EDIT_JACKPOT_JUNGSU         1079
#define IDC_STATIC_COUNT                1079
#define IDC_EDIT_TNOTIC                 1079
#define IDC_EDIT_JACKPOT_GOSU           1080
#define IDC_EDIT_SAMEIPLIMIT            1080
#define IDC_EDIT_JACKPOT_DOSIN          1081
#define IDC_EDIT_JACKPOT_FREE           1082
#define IDC_CHECK_SAVE                  1083
#define IDC_CHECK_MACADDR               1083
#define IDC_EDIT_JACKPOT_CHOBOS         1083
#define IDC_EDIT_JACKPOT_JUNGSUS        1084
#define IDC_EDIT_BSSO                   1085
#define IDC_EDIT_JACKPOT_GOSUS          1085
#define IDC_EDIT_BEVENT                 1086
#define IDC_EDIT_JACKPOT_DOSINS         1086
#define IDC_EDIT_JACKPOT_FREES          1087
#define IDC_EDIT_JACKPOT_CHOBOF         1088
#define IDC_EDIT_JACKPOT_JUNGSUF        1089
#define IDC_EDIT_JACKPOT_GOSUF          1090
#define IDC_EDIT_JACKPOT_DOSINF         1091
#define IDC_EDIT_JACKPOT_FREEF          1092
#define IDC_BUTTON_SA                   1096
#define IDC_EDIT_NORMAL                 1097
#define IDC_CHECK_LIMIT                 1098
#define IDC_EDIT_LEADERS                1099
#define IDC_EDIT_LDAP_HOST0             1100
#define IDC_EDIT_LEADERSPLUS            1100
#define IDC_EDIT_LDAP_HOST1             1101
#define IDC_STATIC_NOR                  1101
#define IDC_EDIT_LDAP_HOST2             1102
#define IDC_STATIC_LEADERS              1102
#define IDC_EDIT_LDAP_HOST3             1103
#define IDC_STATIC_LEADERSP             1103
#define IDC_EDIT_LDAP_UID               1104
#define IDC_EDIT_SAFEMIN                1104
#define IDC_EDIT_LDAP_PASS              1105
#define IDC_STATIC_SAFEMIN              1105
#define IDC_EDIT_SAFEMAX                1106
#define IDC_STATIC_SAFEMAX              1107
#define ID_VIEW_SWITCHMODE              32771
#define ID_VIEW_CONFIG4                 32771
#define ID_VIEW_CONFIG                  32772
#define IDM_SET_ADMIN                   32773
#define IDM_SET_CAPTUREID               32774
#define IDM_SET_SEARCH                  32775
#define ID_VIEW_CONFIGEVENT             32776
#define ID_VIEW_CONFIGSA                32777
#define ID_TEST                         32778
#define ID_FILE_CONNECTDENY             61204
#define ID_TOOL_FORCETERMINATEDBTHREAD  61205
#define ID_VIEW_CONFIG2                 61206
#define ID_VIEW_CONFIG3                 61207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
